'use strict';function t(e,a,b,c){e.v.yc(e.ib,a,b,c,void 0)}function C(e,a,b,c){e.v.ha?t(e,a,b,c):e.v.Ff()._OnMessageFromDOM({type:"event",component:e.ib,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function D(e,a,b){e.v.F(e.ib,a,b)}function G(e,a){for(const [b,c]of a)D(e,b,c)}function L(e){e.Zb||(e.v.qf(e.ye),e.Zb=!0)}window.sa=class{constructor(e,a){this.v=e;this.ib=a;this.Zb=!1;this.ye=()=>this.Ka()}ud(){}Ka(){}};function M(e){-1!==e.Xa&&(self.clearTimeout(e.Xa),e.Xa=-1)}
window.df=class{constructor(e,a){this.Zc=e;this.Hh=a;this.Xa=-1;this.$b=-Infinity;this.ze=()=>{this.Xa=-1;this.$b=Date.now();this.nb=!0;this.Zc();this.nb=!1};this.ce=this.nb=!1}c(){M(this);this.ze=this.Zc=null}};"use strict";function N(e,a){const b=a.elementId,c=e.pc(b,a);e.ca.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{O(e,"elem-focused",b)});c.addEventListener("blur",()=>{O(e,"elem-blurred",b)});e.Ub&&document.body.appendChild(c)}
function Q(e,a,b){D(e,a,c=>{const f=e.ca.get(c.elementId);return b(f,c)})}function O(e,a,b,c){c||(c={});c.elementId=b;t(e,a,c)}function R(e,a,b,c){c||(c={});c.elementId=b;C(e,a,c)}
window.yd=class extends self.sa{constructor(e,a){super(e,a);this.ca=new Map;this.Ub=!0;G(this,[["create",b=>N(this,b)],["destroy",b=>{{b=b.elementId;const c=this.ca.get(b);this.Ub&&c.parentElement.removeChild(c);this.ca.delete(b)}}],["set-visible",b=>{this.Ub&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ub){var c=this.ca.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.ca.get(b.elementId);this.cb(c,b)}}],["focus",b=>this.Tc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}pc(){throw Error("required override");}cb(){throw Error("required override");}Tc(e){var a=this.ca.get(e.elementId);e.focus?
a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(p){const d=document.createElement("script");d.async=!1;d.type="module";return p.Sh?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=p.Wh+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=p;document.head.appendChild(d)})}let c=!1,f=!1;function m(){if(!c){try{new Worker("blob://",{get type(){f=!0}})}catch(p){}c=!0}return f}const n=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let u=new Audio;const z={"audio/webm; codecs=opus":!!u.canPlayType("audio/webm; codecs=opus")&&!n,"audio/ogg; codecs=opus":!!u.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!u.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!u.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!u.canPlayType("audio/mp4"),"audio/mpeg":!!u.canPlayType("audio/mpeg")};u=null;async function F(p){p=
await x(p);return(new TextDecoder("utf-8")).decode(p)}function x(p){return new Promise((d,k)=>{const l=new FileReader;l.onload=q=>d(q.target.result);l.onerror=q=>k(q);l.readAsArrayBuffer(p)})}const y=[];let E=0;window.RealFile=window.File;const H=[],B=new Map,I=new Map;let K=0;const P=[];self.runOnStartup=function(p){if("function"!==typeof p)throw Error("runOnStartup called without a function");P.push(p)};const g=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.$=class p{constructor(d){this.ha=
d.Yh;this.wa=null;this.H="";this.kc=d.Vh;this.Cb={};this.Qa=this.Bb=null;this.Xb=[];this.qb=this.N=this.Va=null;this.Ua=-1;this.Mh=()=>this.Ag();this.Ta=[];this.s=d.Ae;this.ob="file"===location.protocol.substr(0,4);!this.ha||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ha=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ha=!1;if("cordova"===this.s&&this.ha)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ha=!1)}else this.ha=!1;this.bc=this.na=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.ob||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.F("runtime","cordova-fetch-local-file",k=>this.Uf(k));this.F("runtime","create-job-worker",()=>this.Vf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Nd(d)):this.Nd(d)}c(){this.Ec();this.wa&&(this.wa=this.wa.onmessage=
null);this.Bb&&(this.Bb.terminate(),this.Bb=null);this.Qa&&(this.Qa.c(),this.Qa=null);this.N&&(this.N.parentElement.removeChild(this.N),this.N=null)}wc(){return e&&"cordova"===this.s}xc(){const d=navigator.userAgent;return e&&g.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async Nd(d){"macos-wkwebview"===this.s&&this.Xc({type:"ready"});if("playable-ad"===this.s){this.na=self.c3_base64files;this.bc={};await this.vf();for(let l=0,q=d.Ya.length;l<q;++l){var k=d.Ya[l].toLowerCase();
this.bc.hasOwnProperty(k)?d.Ya[l]={Sh:!0,Wh:this.bc[k]}:this.na.hasOwnProperty(k)&&(d.Ya[l]=URL.createObjectURL(this.na[k]))}}d.Nh?this.H=d.Nh:(k=location.origin,this.H=("null"===k?"file:///":k)+location.pathname,k=this.H.lastIndexOf("/"),-1!==k&&(this.H=this.H.substr(0,k+1)));d.$h&&(this.Cb=d.$h);k=new MessageChannel;this.wa=k.port1;this.wa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.pg(l));this.qb=new self.$e(this);await S(this.qb);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ha?await this.If(d,k.port2):await this.Hf(d,k.port2)}Jc(d){d=this.Cb.hasOwnProperty(d)?this.Cb[d]:d.endsWith("/workermain.js")&&this.Cb.hasOwnProperty("workermain.js")?this.Cb["workermain.js"]:"playable-ad"===this.s&&this.na.hasOwnProperty(d.toLowerCase())?this.na[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async qc(d,k,
l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===this.s&&this.ob)return d=await this.Db(l.Rh?d:this.kc+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}Da(){return Math.max(window.innerWidth,1)}Ca(){return Math.max(window.innerHeight,1)}Ld(d){var k=
this.qb;return{baseUrl:this.H,windowInnerWidth:this.Da(),windowInnerHeight:this.Ca(),devicePixelRatio:window.devicePixelRatio,isFullscreen:p.ab(),projectData:d.fi,previewImageBlobs:window.cr_previewImageBlobs||this.na,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.di||"",exportType:d.Ae,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ei,jobScheduler:{inputPort:k.ed,outputPort:k.md,maxNumWorkers:k.Jh},supportedAudioFormats:z,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.kc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.kc+"opus.wasm.wasm",isFileProtocol:this.ob,isiOSCordova:this.wc(),isiOSWebView:this.xc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async If(d,k){var l=this.Jc(d.Zh);this.Bb=await this.qc(l,this.H,{type:"module",name:"Runtime",Rh:!0});this.N=document.createElement("canvas");this.N.style.display="none";l=this.N.transferControlToOffscreen();document.body.appendChild(this.N);
window.c3canvas=this.N;let q=d.td||[],v=d.Ya;q=await Promise.all(q.map(r=>this.La(r)));v=await Promise.all(v.map(r=>this.La(r)));if("cordova"===this.s)for(let r=0,w=d.nc.length;r<w;++r){const A=d.nc[r],J=A[0];if(J===d.rd||"scriptsInEvents.js"===J||J.endsWith("/scriptsInEvents.js"))A[1]=await this.La(J)}this.Bb.postMessage(Object.assign(this.Ld(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:q,engineScripts:v,projectScripts:d.nc,mainProjectScript:d.rd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...T(this.qb)]);this.Xb=H.map(r=>new r(this));this.Kd();self.c3_callFunction=(r,w)=>this.Va.Lf(r,w);"preview"===this.s&&(self.goToLastErrorScript=()=>this.yc("runtime","go-to-last-error-script"))}async Hf(d,k){this.N=document.createElement("canvas");this.N.style.display="none";document.body.appendChild(this.N);window.c3canvas=this.N;this.Xb=H.map(r=>new r(this));this.Kd();var l=d.Ya.map(r=>"string"===typeof r?(new URL(r,this.H)).toString():r);Array.isArray(d.td)&&l.unshift(...d.td);l=await Promise.all(l.map(r=>
this.La(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const q=d.rd,v=d.nc;for(let [r,w]of v)if(w||(w=r),r===q)try{w=await this.La(w),await b(w),"preview"!==this.s||l[r]||this.Yd(r,"main script did not run to completion")}catch(A){this.Yd(r,A)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))w=await this.La(w),await b(w);"preview"===this.s&&"object"!==typeof self.ai.bi?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.Ld(d),{isInWorker:!1,messagePort:k,canvas:this.N,runOnStartupFunctions:P}),this.Qd(),this.Qa=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Qa,d))}Yd(d,k){this.Pb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Qd(){this.Pb()}Pb(){const d=
window.Oh;d&&(d.parentElement.removeChild(d),window.Oh=null)}async Vf(){const d=await U(this.qb);return{outputPort:d,transferables:[d]}}Ff(){if(this.ha)throw Error("not available in worker mode");return this.Qa}yc(d,k,l,q,v){this.wa.postMessage({type:"event",component:d,handler:k,dispatchOpts:q||null,data:l,responseId:null},v)}Dd(d,k,l,q,v){const r=K++,w=new Promise((A,J)=>{I.set(r,{resolve:A,reject:J})});this.wa.postMessage({type:"event",component:d,handler:k,dispatchOpts:q||null,data:l,responseId:r},
v);return w}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.bg(d);if("result"===k)this.Ig(d);else if("runtime-ready"===k)this.Jg();else if("alert-error"===k)this.Pb(),alert(d.message);else if("creating-runtime"===k)this.Qd();else throw Error(`unknown message '${k}'`);}bg(d){const k=d.component,l=d.handler,q=d.data,v=d.responseId;if(d=B.get(k))if(d=d.get(l)){var r=null;try{r=d(q)}catch(w){console.error(`Exception in '${k}' handler '${l}':`,w);null!==v&&this.Ob(v,!1,""+w);return}if(null===
v)return r;r&&r.then?r.then(w=>this.Ob(v,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${l}':`,w);this.Ob(v,!1,""+w)}):this.Ob(v,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ob(d,k,l){let q;l&&l.transferables&&(q=l.transferables);this.wa.postMessage({type:"result",responseId:d,isOk:k,result:l},q)}Ig(d){const k=d.responseId,l=d.isOk;d=d.result;const q=I.get(k);l?q.resolve(d):q.reject(d);I.delete(k)}F(d,
k,l){let q=B.get(d);q||(q=new Map,B.set(d,q));if(q.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);q.set(k,l)}static ia(d){if(H.includes(d))throw Error("DOM handler already added");H.push(d)}Kd(){for(const d of this.Xb)if("runtime"===d.ib){this.Va=d;return}throw Error("cannot find runtime DOM handler");}pg(d){this.yc("debugger","message",d)}Jg(){for(const d of this.Xb)d.ud()}static ab(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Qb(d){h=!!d}qf(d){this.Ta.push(d);this.Wc()}gh(d){d=this.Ta.indexOf(d);if(-1===d)throw Error("invalid callback");this.Ta.splice(d,1);this.Ta.length||this.Ec()}Wc(){-1===this.Ua&&this.Ta.length&&(this.Ua=requestAnimationFrame(this.Mh))}Ec(){-1!==this.Ua&&(cancelAnimationFrame(this.Ua),this.Ua=-1)}Ag(){this.Ua=-1;for(const d of this.Ta)d();this.Wc()}Ba(d){this.Va.Ba(d)}Ja(d){this.Va.Ja(d)}Vc(){this.Va.Vc()}Jb(d){this.Va.Jb(d)}Ze(){return!!z["audio/webm; codecs=opus"]}async Fh(d){d=await this.Dd("runtime",
"opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Ye(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}Cd(d){return!this.Ye(d)}async La(d){return"cordova"===this.s&&(d.startsWith("file:")||this.ob&&this.Cd(d))?(d.startsWith(this.H)&&(d=d.substr(this.H.length)),d=await this.Db(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async Uf(d){const k=d.filename;switch(d.as){case "text":return await this.Re(k);case "buffer":return await this.Db(k);
default:throw Error("unsupported type");}}Md(){const d=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof d)throw Error("Permission API is not loaded");return d}Pd(d,k){d=d[k];if("string"!==typeof d)throw Error("Invalid permission name");return d}Gf(d){const k=this.Md();return new Promise((l,q)=>k.checkPermission(this.Pd(k,d),v=>l(!!v.hasPermission),q))}hh(d){const k=this.Md();return new Promise((l,q)=>k.requestPermission(this.Pd(k,d),v=>l(!!v.hasPermission),
q))}async gf(){var d=["RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"];if("cordova"!==this.s||this.wc())return!0;for(const k of d)if(!await this.Gf(k)&&!1===await this.hh(k))return!1;return!0}async hf(){if(!1===await this.gf())throw Error("Permission not granted");}xd(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,q)=>{window.resolveLocalFileSystemURL(k,v=>{v.file(l,q)},q)})}async Re(d){d=await this.xd(d);return await F(d)}Fc(){if(y.length&&!(8<=E)){E++;var d=
y.shift();this.wf(d.filename,d.Xh,d.Qh)}}Db(d){return new Promise((k,l)=>{y.push({filename:d,Xh:q=>{E--;this.Fc();k(q)},Qh:q=>{E--;this.Fc();l(q)}});this.Fc()})}async wf(d,k,l){try{const q=await this.xd(d),v=await x(q);k(v)}catch(q){l(q)}}Xc(d){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async vf(){const d=
[];for(const [k,l]of Object.entries(this.na))d.push(this.uf(k,l));await Promise.all(d)}async uf(d,k){if("object"===typeof k)this.na[d]=new Blob([k.str],{type:k.type}),this.bc[d]=k.str;else{let l=await this.Df(k);l||(l=this.yf(k));this.na[d]=l}}async Df(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}yf(d){d=this.$g(d);return this.tf(d.data,d.Th)}$g(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||"";const q=k[2];l="base64"===k[1]||"base64"===q?atob(l):decodeURIComponent(l);return{Th:d,data:l}}tf(d,k){var l=d.length;let q=l>>2,v=new Uint8Array(l),r=new Uint32Array(v.buffer,0,q),w,A;for(A=w=0;w<q;++w)r[w]=d.charCodeAt(A++)|d.charCodeAt(A++)<<8|d.charCodeAt(A++)<<16|d.charCodeAt(A++)<<24;for(l&=
3;l--;)v[A]=d.charCodeAt(A),++A;return new Blob([v],{type:k})}}}"use strict";
{const e=self.$;function a(g){return g.sourceCapabilities&&g.sourceCapabilities.firesTouchEvents||g.originalEvent&&g.originalEvent.sourceCapabilities&&g.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function n(g){return new Promise((h,p)=>{const d=document.createElement("link");d.onload=()=>h(d);d.onerror=k=>p(k);d.rel=
"stylesheet";d.href=g;document.head.appendChild(d)})}function u(g){return new Promise((h,p)=>{const d=new Image;d.onload=()=>h(d);d.onerror=k=>p(k);d.src=g})}async function z(g){g=URL.createObjectURL(g);try{return await u(g)}finally{URL.revokeObjectURL(g)}}function F(g){return new Promise((h,p)=>{let d=new FileReader;d.onload=k=>h(k.target.result);d.onerror=k=>p(k);d.readAsText(g)})}async function x(g,h,p){if(!/firefox/i.test(navigator.userAgent))return await z(g);var d=await F(g);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const k=d.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),q=k.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await z(g)}k.setAttribute("width",h+"px");k.setAttribute("height",p+"px");d=(new XMLSerializer).serializeToString(d);g=new Blob([d],{type:"image/svg+xml"});return await z(g)}function y(g){do{if(g.parentNode&&g.hasAttribute("contenteditable"))return!0;g=g.parentNode}while(g);return!1}const E=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function B(g){H.has(g.target.tagName.toLowerCase())&&g.preventDefault()}function I(g){(g.metaKey||g.ctrlKey)&&g.preventDefault()}self.C3_GetSvgImageSize=async function(g){g=await z(g);if(0<g.width&&0<g.height)return[g.width,g.height];{g.style.position="absolute";g.style.left="0px";g.style.top="0px";g.style.visibility="hidden";document.body.appendChild(g);const h=g.getBoundingClientRect();document.body.removeChild(g);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(g,h,p,d,k){g=await x(g,h,p);const l=document.createElement("canvas");l.width=d;l.height=k;l.getContext("2d").drawImage(g,0,0,h,p);return l};let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);function P(){try{return window.parent&&window.parent.document.hasFocus()}catch(g){return!1}}e.ia(class extends self.sa{constructor(g){super(g,"runtime");this.ie=!0;this.Wa=-1;this.pd="any";this.Zd=this.$d=!1;this.hd=
this.yb=this.Fa=null;g.F("canvas","update-size",d=>this.Xg(d));g.F("runtime","invoke-download",d=>this.hg(d));g.F("runtime","raster-svg-image",d=>this.Bg(d));g.F("runtime","get-svg-image-size",d=>this.fg(d));g.F("runtime","set-target-orientation",d=>this.Pg(d));g.F("runtime","register-sw",()=>this.Eg());g.F("runtime","post-to-debugger",d=>this.Sd(d));g.F("runtime","go-to-script",d=>this.Sd(d));g.F("runtime","before-start-ticking",()=>this.Qf());g.F("runtime","debug-highlight",d=>this.Yf(d));g.F("runtime",
"enable-device-orientation",()=>this.sf());g.F("runtime","enable-device-motion",()=>this.rf());g.F("runtime","add-stylesheet",d=>this.Pf(d));g.F("runtime","alert",d=>this.Nc(d));g.F("runtime","hide-cordova-splash",()=>this.gg());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const k=d.target;h.has(k.tagName.toLowerCase())||y(k)||d.preventDefault()});const p=g.N;window.addEventListener("selectstart",B);window.addEventListener("gesturehold",B);p.addEventListener("selectstart",
B);p.addEventListener("gesturehold",B);window.addEventListener("touchstart",B,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",B,{passive:!1}),p.addEventListener("pointerdown",B)):p.addEventListener("touchstart",B);this.vb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",()=>this.Yg());window.addEventListener("fullscreenchange",
()=>this.eb());window.addEventListener("webkitfullscreenchange",()=>this.eb());window.addEventListener("mozfullscreenchange",()=>this.eb());window.addEventListener("fullscreenerror",d=>this.Pc(d));window.addEventListener("webkitfullscreenerror",d=>this.Pc(d));window.addEventListener("mozfullscreenerror",d=>this.Pc(d));g.xc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var d=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?k.has(l.type.toLowerCase()||"text"):y(l)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this.Zg(d);this.Ra=new Set;this.cc=new WeakSet;this.va=!1}Qf(){"cordova"===this.v.s?(document.addEventListener("pause",()=>this.Uc(!0)),document.addEventListener("resume",()=>this.Uc(!1))):document.addEventListener("visibilitychange",()=>this.Uc(document.hidden));return{isSuspended:!(!document.hidden&&!K)}}ud(){window.addEventListener("focus",()=>
this.gb("window-focus"));window.addEventListener("blur",()=>{this.gb("window-blur",{parentHasFocus:P()});this.vb=0});window.addEventListener("focusin",h=>{h=h.target;(E.has(h.tagName.toLowerCase())||y(h))&&this.gb("keyboard-blur")});window.addEventListener("keydown",h=>this.Rd("keydown",h));window.addEventListener("keyup",h=>this.Rd("keyup",h));window.addEventListener("dblclick",h=>this.Rc("dblclick",h,c));window.addEventListener("wheel",h=>this.rg(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Kc(h);this.fb("pointerdown",h)}),this.v.ha&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.yb=new self.df(()=>this.Bf(),5),this.yb.ce=!0,window.addEventListener("pointerrawupdate",h=>this.sg(h))):window.addEventListener("pointermove",h=>this.fb("pointermove",h)),window.addEventListener("pointerup",h=>this.fb("pointerup",h)),window.addEventListener("pointercancel",h=>this.fb("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Kc(h);this.Sc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Sc("pointermove",h)),window.addEventListener("mouseup",h=>this.Sc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Kc(h);this.Nb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Nb("pointermove",h)),window.addEventListener("touchend",h=>this.Nb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Nb("pointercancel",h)));const g=()=>this.Vc();window.addEventListener("pointerup",g,!0);window.addEventListener("touchend",
g,!0);window.addEventListener("click",g,!0);window.addEventListener("keydown",g,!0);window.addEventListener("gamepadconnected",g,!0)}gb(g,h){t(this,g,h||null,m)}Da(){return this.v.Da()}Ca(){return this.v.Ca()}Yg(){const g=this.Da(),h=this.Ca();this.gb("window-resize",{innerWidth:g,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.ab()});this.v.xc()&&(-1!==this.Wa&&clearTimeout(this.Wa),this.Ud(g,h,0))}ih(g,h,p){-1!==this.Wa&&clearTimeout(this.Wa);this.Wa=setTimeout(()=>this.Ud(g,
h,p),48)}Ud(g,h,p){const d=this.Da(),k=this.Ca();this.Wa=-1;d!=g||k!=h?this.gb("window-resize",{innerWidth:d,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.ab()}):10>p&&this.ih(d,k,p+1)}Pg(g){this.pd=g.targetOrientation}Bh(){const g=this.pd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(g):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(g):screen.mozLockOrientation?h=screen.mozLockOrientation(g):screen.msLockOrientation&&(h=screen.msLockOrientation(g));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}eb(){const g=e.ab();g&&"any"!==this.pd&&this.Bh();t(this,"fullscreenchange",{isFullscreen:g,innerWidth:this.Da(),innerHeight:this.Ca()})}Pc(g){console.warn("[Construct 3] Fullscreen request failed: ",g);t(this,"fullscreenerror",
{isFullscreen:e.ab(),innerWidth:this.Da(),innerHeight:this.Ca()})}Uc(g){g?this.v.Ec():this.v.Wc();t(this,"visibilitychange",{hidden:g})}Rd(g,h){"Backspace"===h.key&&B(h);const p=b.get(h.code)||h.code;C(this,g,{code:p,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}rg(g){t(this,"wheel",{clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,deltaX:g.deltaX,deltaY:g.deltaY,deltaZ:g.deltaZ,deltaMode:g.deltaMode,
timeStamp:g.timeStamp},c)}Rc(g,h,p){a(h)||C(this,g,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},p)}Sc(g,h){if(!a(h)){var p=this.vb;"pointerdown"===g&&0!==p?g="pointermove":"pointerup"===g&&0!==h.buttons&&(g="pointermove");C(this,g,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.vb=h.buttons;this.Rc(h.type,h,f)}}fb(g,h){if(this.yb&&"pointermove"!==g){var p=this.yb;p.nb||(M(p),p.$b=Date.now())}p=0;"mouse"===h.pointerType&&(p=this.vb);C(this,g,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:p,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);"mouse"===h.pointerType&&(p="mousemove","pointerdown"===g?p="mousedown":"pointerup"===g&&(p="mouseup"),this.Rc(p,h,f),this.vb=h.buttons)}sg(g){this.hd=g;g=this.yb;if(-1===g.Xa){var h=Date.now(),p=h-g.$b,d=g.Hh;p>=d&&g.ce?(g.$b=h,g.nb=!0,g.Zc(),g.nb=!1):g.Xa=self.setTimeout(g.ze,Math.max(d-p,4))}}Bf(){this.fb("pointermove",this.hd);this.hd=null}Nb(g,h){for(let p=0,d=h.changedTouches.length;p<d;++p){const k=h.changedTouches[p];C(this,g,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},c)}}Kc(g){window!==window.top&&window.focus();this.Od(g.target)&&document.activeElement&&!this.Od(document.activeElement)&&document.activeElement.blur()}Od(g){return!g||g===document||
g===window||g===document.body||"canvas"===g.tagName.toLowerCase()}sf(){this.$d||(this.$d=!0,window.addEventListener("deviceorientation",g=>this.$f(g)),window.addEventListener("deviceorientationabsolute",g=>this.ag(g)))}rf(){this.Zd||(this.Zd=!0,window.addEventListener("devicemotion",g=>this.Zf(g)))}$f(g){t(this,"deviceorientation",{absolute:!!g.absolute,alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0,timeStamp:g.timeStamp,webkitCompassHeading:g.webkitCompassHeading,webkitCompassAccuracy:g.webkitCompassAccuracy},
c)}ag(g){t(this,"deviceorientationabsolute",{absolute:!!g.absolute,alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0,timeStamp:g.timeStamp},c)}Zf(g){let h=null;var p=g.acceleration;p&&(h={x:p.x||0,y:p.y||0,z:p.z||0});p=null;var d=g.accelerationIncludingGravity;d&&(p={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const k=g.rotationRate;k&&(d={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});t(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:p,rotationRate:d,interval:g.interval,timeStamp:g.timeStamp},
c)}Xg(g){const h=this.v.N;h.style.width=g.styleWidth+"px";h.style.height=g.styleHeight+"px";h.style.marginLeft=g.marginLeft+"px";h.style.marginTop=g.marginTop+"px";this.ie&&(h.style.display="",this.ie=!1)}hg(g){const h=g.url;g=g.filename;const p=document.createElement("a"),d=document.body;p.textContent=g;p.href=h;p.download=g;d.appendChild(p);p.click();d.removeChild(p)}async Bg(g){var h=g.imageBitmapOpts;g=await self.C3_RasterSvgImageBlob(g.blob,g.imageWidth,g.imageHeight,g.surfaceWidth,g.surfaceHeight);
h=h?await createImageBitmap(g,h):await createImageBitmap(g);return{imageBitmap:h,transferables:[h]}}async fg(g){return await self.C3_GetSvgImageSize(g.blob)}async Pf(g){await n(g.url)}Vc(){var g=[...this.Ra];this.Ra.clear();if(!this.va)for(const h of g)(g=h.play())&&g.catch(()=>{this.cc.has(h)||this.Ra.add(h)})}Ba(g){if("function"!==typeof g.play)throw Error("missing play function");this.cc.delete(g);let h;try{h=g.play()}catch(p){this.Ra.add(g);return}h&&h.catch(()=>{this.cc.has(g)||this.Ra.add(g)})}Ja(g){this.Ra.delete(g);
this.cc.add(g)}Jb(g){this.va=!!g}gg(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Yf(g){if(g.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var h=this.Fa;h.style.display="";h.style.left=g.left-1+"px";h.style.top=g.top-1+"px";h.style.width=g.width+2+"px";h.style.height=g.height+2+"px";h.textContent=g.name}else this.Fa&&(this.Fa.style.display="none")}Eg(){window.C3_RegisterSW&&window.C3_RegisterSW()}Sd(g){window.c3_postToMessagePort&&
(g.from="runtime",window.c3_postToMessagePort(g))}Lf(g,h){return this.v.Dd(this.ib,"js-invoke-function",{name:g,params:h},void 0,void 0)}Nc(g){alert(g.message)}Zg(g){"entered-fullscreen"===g?(e.Qb(!0),this.eb()):"exited-fullscreen"===g?(e.Qb(!1),this.eb()):console.warn("Unknown wrapper message: ",g)}})}"use strict";
async function S(e){if(e.Gh)throw Error("already initialised");e.Gh=!0;var a=e.jc.Jc("dispatchworker.js");e.ad=await e.jc.qc(a,e.H,{name:"DispatchWorker"});a=new MessageChannel;e.ed=a.port1;e.ad.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.md=await U(e)}function T(e){return[e.ed,e.md]}
async function U(e){const a=e.je.length;var b=e.jc.Jc("jobworker.js");b=await e.jc.qc(b,e.H,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;e.ad.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);e.je.push(b);return f.port1}
self.$e=class{constructor(e){this.jc=e;this.H=e.H;this.H="preview"===e.s?this.H+"workers/":this.H+e.kc;this.Jh=Math.min(navigator.hardwareConcurrency||2,16);this.ad=null;this.je=[];this.md=this.ed=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.$({Yh:!1,Zh:"workermain.js",Ya:["scripts/c3runtime.js"],nc:[],rd:"",Vh:"scripts/",td:[],Ae:"html5"}));"use strict";
async function V(e,a){a=a.type;let b=!0;0===a?b=await W():1===a&&(b=await X());t(e,"permission-result",{type:a,result:b})}async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.$.ia(class extends self.sa{constructor(e){super(e,"touch");D(this,"request-permission",a=>V(this,a))}});"use strict";
function aa(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(e,"sw-message",a.data))}
function ba(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.$.ia(class extends self.sa{constructor(e){super(e,"browser");this.s="";G(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>aa(this)],
["alert",a=>this.Nc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Tc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ba(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const c=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.ci||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.$.Qb(!0),this.v.Xc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.$.Qb(!1),this.v.Xc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{t(this,"backbutton")})}Nc(e){alert(e.message)}Tc(e){e=e.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";
{const e=180/Math.PI;self.ja=class extends self.sa{constructor(a){super(a,"audio");this.Wb=this.f=null;this.Yb=this.dd=!1;this.ya=()=>this.Ch();this.fa=[];this.G=[];this.ma=null;this.le="";this.me=-1;this.xb=new Map;this.jd=1;this.va=!1;this.qd=0;this.lc=1;this.bd=0;this.qe="HRTF";this.de="inverse";this.se=600;this.pe=1E4;this.ue=1;this.fe=this.od=!1;this.xe=this.v.Ze();this.ga=new Map;this.Oa=new Set;this.fd=!1;this.kd="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.qg(b,c);this.Vb=null;
self.C3Audio_GetOutputStream=()=>this.dg();self.C3Audio_DOMInterface=this;G(this,[["create-audio-context",b=>this.xf(b)],["play",b=>this.ah(b)],["stop",b=>this.zh(b)],["stop-all",()=>this.Ah()],["set-paused",b=>this.sh(b)],["set-volume",b=>this.xh(b)],["fade-volume",b=>this.Cf(b)],["set-master-volume",b=>this.qh(b)],["set-muted",b=>this.rh(b)],["set-silent",b=>this.uh(b)],["set-looping",b=>this.ph(b)],["set-playback-rate",b=>this.th(b)],["seek",b=>this.jh(b)],["preload",b=>this.bh(b)],["unload",b=>
this.Dh(b)],["unload-all",()=>this.Eh()],["set-suspended",b=>this.vh(b)],["add-effect",b=>this.Id(b)],["set-effect-param",b=>this.mh(b)],["remove-effects",b=>this.eh(b)],["tick",b=>this.Wg(b)],["load-state",b=>this.Qc(b)]])}async xf(a){a.isiOSCordova&&(this.od=!0);this.qd=a.timeScaleMode;this.qe=["equalpower","HRTF","soundfield"][a.panningModel];this.de=["linear","inverse","exponential"][a.distanceModel];this.se=a.refDistance;this.pe=a.maxDistance;this.ue=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.xe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Jd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.Jd()};this.Wb=this.f.createGain();this.Wb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.rc();try{await Promise.all(a.preloadList.map(c=>this.Lb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}Jd(){this.Yb||(this.dd=!1,window.addEventListener("pointerup",this.ya,!0),window.addEventListener("touchend",this.ya,!0),window.addEventListener("click",this.ya,!0),window.addEventListener("keydown",this.ya,!0),this.Yb=!0)}zf(){this.Yb&&(this.dd=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",
this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",this.ya,!0),this.Yb=!1)}Ch(){if(!this.dd){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.zf()}}Z(){return this.f}rc(){return this.f.currentTime}za(){return this.Wb}Ad(a){return(a=this.ga.get(a.toLowerCase()))?a[0].T():this.za()}Be(a,b){a=a.toLowerCase();let c=this.ga.get(a);
c||(c=[],this.ga.set(a,c));b.oh(c.length);b.wh(a);c.push(b);this.Xd(a)}Xd(a){let b=this.za();const c=this.ga.get(a);if(c&&c.length){b=c[0].T();for(let f=0,m=c.length;f<m;++f){const n=c[f];f+1===m?n.V(this.za()):n.V(c[f+1].T())}}for(const f of this.ra(a))f.ef(b);this.Ga&&this.kd===a&&(this.Ga.disconnect(),this.Ga.connect(b))}Fb(){return this.jd}Gb(){return this.va}nh(){this.fe=!0}Te(a,b){return b?this.v.Fh(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):
new Promise((c,f)=>{this.f.decodeAudioData(a,c,f)})}Ba(a){this.v.Ba(a)}Ja(a){this.v.Ja(a)}Ed(a){let b=0;for(let c=0,f=this.G.length;c<f;++c){const m=this.G[c];this.G[b]=m;m.O===a?m.c():++b}this.G.length=b}ff(){let a=0;for(let b=0,c=this.fa.length;b<c;++b){const f=this.fa[b];this.fa[a]=f;f.Aa()?f.c():++a}this.fa.length=a}*ra(a){if(a)for(const b of this.G)self.ja.Ue(b.da,a)&&(yield b);else this.ma&&!this.ma.W()&&(yield this.ma)}async Lb(a,b,c,f,m){for(const n of this.fa)if(n.$a()===b)return await Y(n),
n;if(m)return null;f&&(this.od||this.fe)&&this.ff();m="audio/webm; codecs=opus"===c&&!this.xe;f&&m&&this.nh();a=!f||this.od||m?new self.Pe(this,a,b,c,f,m):new self.Ne(this,a,b,c,f);this.fa.push(a);await Y(a);return a}async Hc(a,b,c,f,m){for(const n of this.G)if(n.$a()===b&&(n.oc()||m))return n.kf(f),n;a=await this.Lb(a,b,c,m);f="html5"===a.Yc?new self.Oe(a.i,a,f):new self.Qe(a.i,a,f);this.G.push(f);return f}pf(a){let b=this.xb.get(a);if(!b){let c=null;b={sd:0,Uh:new Promise(f=>c=f),resolve:c};this.xb.set(a,
b)}b.sd++}fh(a){const b=this.xb.get(a);if(!b)throw Error("expected pending tag");b.sd--;0===b.sd&&(b.resolve(),this.xb.delete(a))}Dc(a){a||(a=this.le);return(a=this.xb.get(a))?a.Uh:Promise.resolve()}Mb(){if(0<this.Oa.size)L(this);else for(const a of this.G)if(a.Bd()){L(this);break}}Ka(){for(var a of this.Oa)a.Ka();a=this.rc();for(var b of this.G)b.Ka(a);b=this.G.filter(c=>c.Bd()).map(c=>c.Za());t(this,"state",{tickCount:this.me,audioInstances:b,analysers:[...this.Oa].map(c=>c.We())});0===b.length&&
0===this.Oa.size&&this.Zb&&(this.v.gh(this.ye),this.Zb=!1)}zc(a,b,c){t(this,"trigger",{type:a,tag:b,aiid:c})}async ah(a){const b=a.originalUrl,c=a.url,f=a.type,m=a.isMusic,n=a.tag,u=a.isLooping,z=a.vol,F=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.le=n;this.pf(n);try{this.ma=await this.Hc(b,c,f,n,m),x?(this.ma.Ib(!0),this.ma.jf(x.x,x.y,x.angle,
x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ma.lf(x.uid)):this.ma.Ib(!1),this.ma.Play(u,z,F,y)}catch(E){console.error("[Construct 3] Audio: error starting playback: ",E);return}finally{this.fh(n)}L(this)}zh(a){a=a.tag;for(const b of this.ra(a))b.ua()}Ah(){for(const a of this.G)a.ua()}sh(a){const b=a.tag;a=a.paused;for(const c of this.ra(b))a?c.bb():c.Hb();this.Mb()}xh(a){const b=a.tag;a=a.vol;for(const c of this.ra(b))c.Kb(a)}async Cf(a){const b=a.tag,c=a.vol,f=a.duration;
a=a.stopOnEnd;await this.Dc(b);for(const m of this.ra(b))m.Ve(c,f,a);this.Mb()}qh(a){this.jd=a.vol;for(const b of this.G)b.Sb()}rh(a){const b=a.tag;a=a.isMuted;for(const c of this.ra(b))c.Fd(a)}uh(a){this.va=a.isSilent;this.v.Jb(this.va);for(const b of this.G)b.Rb()}ph(a){const b=a.tag;a=a.isLooping;for(const c of this.ra(b))c.Bc(a)}async th(a){const b=a.tag;a=a.rate;await this.Dc(b);for(const c of this.ra(b))c.Hd(a)}async jh(a){const b=a.tag;a=a.pos;await this.Dc(b);for(const c of this.ra(b))c.Ac(a)}async bh(a){const b=
a.originalUrl,c=a.url,f=a.type;a=a.isMusic;try{await this.Hc(b,c,f,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Dh(a){if(a=await this.Lb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.fa.indexOf(a),-1!==a&&this.fa.splice(a,1)}Eh(){for(const a of this.fa)a.c();this.fa.length=0}vh(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.G)b.Cc(a);a&&this.f.suspend&&this.f.suspend()}Wg(a){this.lc=a.timeScale;this.bd=a.gameTime;this.me=a.tickCount;if(0!==
this.qd)for(var b of this.G)b.Ma();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.G)f.la===a&&f.Gd(c.x,c.y,c.angle)}}async Id(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.He(this,...f);else if("delay"===b)f=new self.Fe(this,...f);else if("convolution"===b){b=null;try{b=await this.Lb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}f=new self.Ee(this,b.ea,...f);f.kh(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.Ie(this,...f);else if("phaser"===b)f=new self.Ke(this,...f);else if("gain"===b)f=new self.Je(this,...f);else if("tremolo"===b)f=new self.Me(this,...f);else if("ringmod"===b)f=new self.Le(this,...f);else if("distortion"===b)f=new self.Ge(this,...f);else if("compressor"===b)f=new self.De(this,...f);else if("analyser"===b)f=new self.Ce(this,...f);else throw Error("invalid effect type");this.Be(c,
f);this.Wd()}mh(a){const b=a.index,c=a.param,f=a.value,m=a.ramp,n=a.time;a=this.ga.get(a.tag);!a||0>b||b>=a.length||(a[b].ba(c,f,m,n),this.Wd())}eh(a){a=a.tag.toLowerCase();const b=this.ga.get(a);if(b&&b.length){for(const c of b)c.c();this.ga.delete(a);this.Xd(a)}}nf(a){this.Oa.add(a);this.Mb()}dh(a){this.Oa.delete(a)}Wd(){this.fd||(this.fd=!0,Promise.resolve().then(()=>this.Af()))}Af(){const a={};for(const [b,c]of this.ga)a[b]=c.map(f=>f.Za());t(this,"fxstate",{fxstate:a});this.fd=!1}async Qc(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.G)c.Aa()&&1===b||(c.Aa()||2!==b)&&c.ua();for(const f of this.ga.values())for(const m of f)m.c();this.ga.clear();this.lc=a.timeScale;this.bd=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.va=a.isSilent;this.v.Jb(this.va);this.jd=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(m=>this.Id(m))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.Mf(f,b)));this.Mb()}async Mf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,f=a.bufferUrl,m=a.bufferType,n=a.isMusic,u=a.tag,z=a.isLooping,F=a.volume,x=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.Hc(c,f,m,u,n)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.cf(a.pan);b.Play(z,F,x,0);a.isPlaying||b.bb();b.Mc(a)}}}qg(a,b){this.Ga&&this.Ga.disconnect();this.kd=b.toLowerCase();this.Ga=this.f.createMediaStreamSource(a);this.Ga.connect(this.Ad(this.kd))}dg(){this.Vb||(this.Vb=this.f.createMediaStreamDestination(),
this.Wb.connect(this.Vb));return this.Vb.stream}static Ue(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static mf(a){return a*e}static Se(a){return Math.pow(10,a/20)}static zd(a){return Math.max(Math.min(self.ja.Se(a),1),0)}static bf(a){return Math.log(a)/Math.log(10)*20}static af(a){return self.ja.bf(Math.max(Math.min(a,1),0))}static Ph(a,b){return 1-Math.exp(-b*a)}};self.$.ia(self.ja)}"use strict";function Y(e){e.ac||(e.ac=e.Lc());return e.ac}
self.vd=class{constructor(e,a,b,c,f){this.i=e;this.Lh=a;this.Ha=b;this.U=c;this.Ih=f;this.Yc="";this.ac=null}c(){this.ac=this.i=null}Lc(){}Z(){return this.i.Z()}tc(){return this.Lh}$a(){return this.Ha}sc(){return this.U}Aa(){return this.Ih}ka(){}};"use strict";
self.Ne=class extends self.vd{constructor(e,a,b,c,f){super(e,a,b,c,f);this.Yc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.rb=this.sb=null;this.M.addEventListener("canplaythrough",()=>!0);this.wb=this.Z().createGain();this.ub=null;this.M.addEventListener("canplay",()=>{this.sb&&(this.sb(),this.rb=this.sb=null);!this.ub&&this.M&&(this.ub=this.Z().createMediaElementSource(this.M),this.ub.connect(this.wb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ha}' error: `,m);this.rb&&(this.rb(m),this.rb=this.sb=null)})}c(){this.i.Ed(this);this.wb.disconnect();this.wb=null;this.ub.disconnect();this.ub=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.c()}Lc(){return new Promise((e,a)=>{this.sb=e;this.rb=a;this.M.src=this.Ha})}S(){return this.M}ka(){return this.M.duration}};"use strict";
async function ca(e){if(e.Ea)return e.Ea;var a=e.i.v;if("cordova"===a.s&&a.Cd(e.Ha)&&a.ob)e.Ea=await a.Db(e.Ha);else{a=await fetch(e.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.Ea=await a.arrayBuffer()}}async function da(e){if(e.ea)return e.ea;e.ea=await e.i.Te(e.Ea,e.Kh);e.Ea=null}
self.Pe=class extends self.vd{constructor(e,a,b,c,f,m){super(e,a,b,c,f);this.Yc="webaudio";this.ea=this.Ea=null;this.Kh=!!m}c(){this.i.Ed(this);this.ea=this.Ea=null;super.c()}async Lc(){try{await ca(this),await da(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ha}': `,e)}}ka(){return this.ea?this.ea.duration:0}};"use strict";
{let e=0;self.wd=class{constructor(a,b,c){this.i=a;this.O=b;this.da=c;this.Tb=e++;this.P=this.Z().createGain();this.P.connect(this.za());this.D=null;this.pb=!1;this.pa=[0,0,0];this.oa=[0,0,0];this.J=!0;this.Y=this.qa=this.I=!1;this.Ab=1;this.Pa=!1;this.xa=1;a=this.i.qd;this.gd=1===a&&!this.Aa()||2===a;this.lb=this.la=-1;this.we=!1}c(){this.O=this.i=null;this.D&&(this.D.disconnect(),this.D=null);this.P.disconnect();this.P=null}Z(){return this.i.Z()}za(){return this.i.Ad(this.da)}Fb(){return this.i.Fb()}Eb(){return this.gd?
this.i.bd:performance.now()/1E3}tc(){return this.O.tc()}$a(){return this.O.$a()}sc(){return this.O.sc()}Aa(){return this.O.Aa()}kf(a){this.da=a}W(){}oc(){}IsPlaying(){return!this.J&&!this.I&&!this.W()}Bd(){return!this.J&&!this.W()}Ia(){}ka(){return this.O.ka()}Play(){}ua(){}bb(){}Hb(){}Kb(a){this.Ab=a;this.P.gain.cancelScheduledValues(0);this.lb=-1;this.P.gain.value=this.uc()}Ve(a,b,c){if(!this.Pa){a*=this.Fb();var f=this.P.gain;f.cancelScheduledValues(0);var m=this.i.rc();b=m+b;f.setValueAtTime(f.value,
m);f.linearRampToValueAtTime(a,b);this.Ab=a;this.lb=b;this.we=c}}Sb(){this.Kb(this.Ab)}Ka(a){-1!==this.lb&&a>=this.lb&&(this.lb=-1,this.we&&this.ua(),this.i.zc("fade-ended",this.da,this.Tb))}uc(){const a=this.Ab*this.Fb();return isFinite(a)?a:0}Fd(a){a=!!a;this.Pa!==a&&(this.Pa=a,this.Rb())}Gb(){return this.i.Gb()}Rb(){}Bc(){}Hd(a){this.xa!==a&&(this.xa=a,this.Ma())}Ma(){}Ac(){}Cc(){}Ib(a){a=!!a;this.pb!==a&&((this.pb=a)?(this.D||(this.D=this.Z().createPanner(),this.D.panningModel=this.i.qe,this.D.distanceModel=
this.i.de,this.D.refDistance=this.i.se,this.D.maxDistance=this.i.pe,this.D.rolloffFactor=this.i.ue),this.P.disconnect(),this.P.connect(this.D),this.D.connect(this.za())):(this.D.disconnect(),this.P.disconnect(),this.P.connect(this.za())))}jf(a,b,c,f,m,n){this.pb&&(this.Gd(a,b,c),a=self.ja.mf,this.D.coneInnerAngle=a(f),this.D.coneOuterAngle=a(m),this.D.coneOuterGain=n)}Gd(a,b,c){this.pb&&(this.pa[0]=a,this.pa[1]=b,this.pa[2]=0,this.oa[0]=Math.cos(c),this.oa[1]=Math.sin(c),this.oa[2]=0,this.D.setPosition(...this.pa),
this.D.setOrientation(...this.oa))}lf(a){this.la=a}vc(){}ef(a){const b=this.D||this.P;b.disconnect();b.connect(a)}Za(){return{aiid:this.Tb,tag:this.da,duration:this.ka(),volume:this.Ab,isPlaying:this.IsPlaying(),playbackTime:this.Ia(),playbackRate:this.xa,uid:this.la,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.Pa,resumePosition:this.vc(),pan:this.Xe()}}Mc(a){this.Hd(a.playbackRate);this.Fd(a.isMuted)}Xe(){if(!this.D)return null;const a=
this.D;return{pos:this.pa,orient:this.oa,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.la}}cf(a){if(a){this.Ib(!0);a=this.D;var b=a.pos;this.pa[0]=b[0];this.pa[1]=b[1];this.pa[2]=b[2];b=a.orient;this.oa[0]=b[0];this.oa[1]=b[1];this.oa[2]=b[2];a.setPosition(...this.pa);a.setOrientation(...this.oa);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.la=a.uid}else this.Ib(!1)}}}"use strict";
self.Oe=class extends self.wd{constructor(e,a,b){super(e,a,b);this.O.wb.connect(this.P);this.O.onended=()=>this.Oc()}c(){this.ua();this.O.wb.disconnect();super.c()}S(){return this.O.S()}Oc(){this.J=!0;this.la=-1;this.i.zc("ended",this.da,this.Tb)}W(){return this.S().ended}oc(){return this.J?!0:this.W()}Ia(){let e=this.S().currentTime;this.Y||(e=Math.min(e,this.ka()));return e}Play(e,a,b){const c=this.S();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Kb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.O.$a()}' to position '${b}': `,f)}this.i.Ba(c);this.I=this.J=!1;this.Y=e;this.xa=1}ua(){const e=this.S();e.paused||e.pause();this.i.Ja(e);this.J=!0;this.I=!1;this.la=-1}bb(){if(!(this.I||this.J||this.W())){var e=this.S();e.paused||e.pause();this.i.Ja(e);this.I=!0}}Hb(){!this.I||this.J||this.W()||(this.i.Ba(this.S()),this.I=!1)}Rb(){this.S().muted=this.Pa||this.Gb()}Bc(e){e=!!e;this.Y!==e&&
(this.Y=e,this.S().loop=e)}Ma(){let e=this.xa;this.gd&&(e*=this.i.lc);try{this.S().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}Ac(e){if(!this.J&&!this.W())try{this.S().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}vc(){return this.Ia()}Cc(e){e?this.IsPlaying()?(this.S().pause(),this.qa=!0):this.qa=!1:this.qa&&(this.i.Ba(this.S()),this.qa=!1)}};"use strict";
function Z(e){e.j&&e.j.disconnect();e.j=null;e.hb=null}
self.Qe=class extends self.wd{constructor(e,a,b){super(e,a,b);this.j=null;this.dc=c=>this.Oc(c);this.cd=!0;this.hb=null;this.R=this.ec=this.fc=0;this.ld=1}c(){this.ua();Z(this);this.dc=null;super.c()}Oc(e){this.I||this.qa||e.target!==this.hb||(this.J=this.cd=!0,this.la=-1,Z(this),this.i.zc("ended",this.da,this.Tb))}W(){return!this.J&&this.j&&this.j.loop||this.I?!1:this.cd}oc(){return!this.j||this.J?!0:this.W()}Ia(){let e;e=this.I?this.R:this.ec+(this.Eb()-this.fc)*this.xa;this.Y||(e=Math.min(e,this.ka()));
return e}Play(e,a,b,c){this.ld=1;this.Kb(a);Z(this);this.j=this.Z().createBufferSource();this.j.buffer=this.O.ea;this.j.connect(this.P);this.hb=this.j;this.j.onended=this.dc;this.j.loop=e;this.j.start(c,b);this.I=this.J=this.cd=!1;this.Y=e;this.xa=1;this.fc=this.Eb();this.ec=b}ua(){if(this.j)try{this.j.stop(0)}catch(e){}this.J=!0;this.I=!1;this.la=-1}bb(){this.I||this.J||this.W()||(this.R=this.Ia(),this.Y&&(this.R%=this.ka()),this.I=!0,this.j.stop(0))}Hb(){!this.I||this.J||this.W()||(Z(this),this.j=
this.Z().createBufferSource(),this.j.buffer=this.O.ea,this.j.connect(this.P),this.hb=this.j,this.j.onended=this.dc,this.j.loop=this.Y,this.Sb(),this.Ma(),this.j.start(0,this.R),this.fc=this.Eb(),this.ec=this.R,this.I=!1)}uc(){return super.uc()*this.ld}Rb(){this.ld=this.Pa||this.Gb()?0:1;this.Sb()}Bc(e){e=!!e;this.Y!==e&&(this.Y=e,this.j&&(this.j.loop=e))}Ma(){let e=this.xa;this.gd&&(e*=this.i.lc);this.j&&(this.j.playbackRate.value=e)}Ac(e){this.J||this.W()||(this.I?this.R=e:(this.bb(),this.R=e,this.Hb()))}vc(){return this.R}Cc(e){e?
this.IsPlaying()?(this.qa=!0,this.R=this.Ia(),this.Y&&(this.R%=this.ka()),this.j.stop(0)):this.qa=!1:this.qa&&(Z(this),this.j=this.Z().createBufferSource(),this.j.buffer=this.O.ea,this.j.connect(this.P),this.hb=this.j,this.j.onended=this.dc,this.j.loop=this.Y,this.Sb(),this.Ma(),this.j.start(0,this.R),this.fc=this.Eb(),this.ec=this.R,this.qa=!1)}Mc(e){super.Mc(e);this.R=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.Z();this.he=-1;this.U=this.da="";this.g=null}c(){this.f=null}oh(a){this.he=a}wh(a){this.da=a}o(){return this.f.createGain()}T(){}V(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var m=this.f.currentTime;f+=m;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,f)}}}Za(){return{type:this.U,tag:this.da,params:this.g}}}
self.He=class extends e{constructor(a,b,c,f,m,n,u){super(a);this.U="filter";this.g=[b,c,f,m,n,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.A=this.f.createBiquadFilter();this.A.type=b;this.A.frequency.value=c;this.A.detune.value=f;this.A.Q.value=m;this.A.gain.vlaue=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}c(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.c()}V(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.A.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.A.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.A.gain,b,c,f)}}};self.Fe=class extends e{constructor(a,b,c,f){super(a);this.U="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.tb=this.o();this.X=this.f.createDelay(b);this.X.delayTime.value=b;this.kb=this.o();this.kb.gain.value=c;this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b);this.tb.connect(this.X);this.X.connect(this.kb);this.kb.connect(this.tb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.tb.disconnect();this.X.disconnect();this.kb.disconnect();super.c()}V(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,b,c,f){const m=self.ja.zd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=m(b);this.m(this.kb.gain,m(b),c,f);break;case 5:this.g[0]=b,this.m(this.X.delayTime,b,c,f)}}};self.Ee=class extends e{constructor(a,b,c,f){super(a);this.U="convolution";this.g=[c,f];this.be=this.ae="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.jb=this.f.createConvolver();this.jb.normalize=c;this.jb.buffer=b;this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b)}c(){this.l.disconnect();this.jb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}V(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}kh(a,b){this.ae=a;this.be=b}Za(){const a=
super.Za();a.bufferOriginalUrl=this.ae;a.bufferUrl="";a.bufferType=this.be;return a}};self.Ie=class extends e{constructor(a,b,c,f,m,n){super(a);this.U="flanger";this.g=[b,c,f,m,n];this.l=this.o();this.a=this.o();this.a.gain.value=1-n/2;this.b=this.o();this.b.gain.value=n/2;this.mb=this.o();this.mb.gain.value=m;this.X=this.f.createDelay(b+c);this.X.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=f;this.K=this.o();this.K.gain.value=c;this.l.connect(this.X);this.l.connect(this.a);
this.X.connect(this.b);this.X.connect(this.mb);this.mb.connect(this.X);this.u.connect(this.K);this.K.connect(this.X.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.X.disconnect();this.u.disconnect();this.K.disconnect();this.a.disconnect();this.b.disconnect();this.mb.disconnect();super.c()}V(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.K.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.mb.gain,b/100,c,f)}}};self.Ke=class extends e{constructor(a,b,c,f,m,n,u){super(a);this.U="phaser";this.g=[b,c,f,m,n,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.A=this.f.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
c;this.A.Q.value=f;this.u=this.f.createOscillator();this.u.frequency.value=n;this.K=this.o();this.K.gain.value=m;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.u.connect(this.K);this.K.connect(this.A.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.K.disconnect();this.a.disconnect();this.b.disconnect();super.c()}V(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.A.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.A.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.K.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,c,f)}}};self.Je=class extends e{constructor(a,b){super(a);this.U="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}V(a){this.h.disconnect();this.h.connect(a)}T(){return this.h}ba(a,b,c,f){const m=self.ja.zd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,f)}}};self.Me=class extends e{constructor(a,b,c){super(a);this.U="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.K=this.o();this.K.gain.value=c/2;this.u.connect(this.K);this.K.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.K.disconnect();this.h.disconnect();super.c()}V(a){this.h.disconnect();this.h.connect(a)}T(){return this.h}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,f);this.m(this.K.gain,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,c,f)}}};self.Le=class extends e{constructor(a,b,c){super(a);this.U="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.zb=this.o();this.zb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.zb.gain);this.u.start(0);this.l.connect(this.zb);this.l.connect(this.a);this.zb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.zb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}V(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}T(){return this.l}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,
f);this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,c,f)}}};self.Ge=class extends e{constructor(a,b,c,f,m,n){super(a);this.U="distortion";this.g=[b,c,f,m,n];this.l=this.o();this.ic=this.o();this.hc=this.o();this.lh(f,m);this.b=this.o();this.b.gain.value=n;this.a=this.o();this.a.gain.value=1-n;this.mc=this.f.createWaveShaper();this.$c=new Float32Array(65536);this.Ef(b,c);this.mc.curve=this.$c;this.l.connect(this.ic);this.l.connect(this.a);this.ic.connect(this.mc);this.mc.connect(this.hc);
this.hc.connect(this.b)}c(){this.l.disconnect();this.ic.disconnect();this.mc.disconnect();this.hc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}lh(a,b){.01>a&&(a=.01);this.ic.gain.value=a;this.hc.gain.value=Math.pow(1/a,.6)*b}Ef(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.yh(f,a,b);this.$c[32768+c]=f;this.$c[32768-c-1]=-f}}yh(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.ja.Ph(f-b,1/c))*(0>a?-1:1)}V(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}T(){return this.l}ba(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.De=class extends e{constructor(a,b,c,f,m,n){super(a);this.U="compressor";this.g=[b,c,f,m,n];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=m;this.h.release.value=n}c(){this.h.disconnect();super.c()}V(a){this.h.disconnect();this.h.connect(a)}T(){return this.h}ba(){}};
self.Ce=class extends e{constructor(a,b,c){super(a);this.U="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.ee=new Float32Array(this.h.frequencyBinCount);this.ve=new Uint8Array(b);this.te=this.Sa=0;this.i.nf(this)}c(){this.i.dh(this);this.h.disconnect();super.c()}Ka(){this.h.getFloatFrequencyData(this.ee);this.h.getByteTimeDomainData(this.ve);const a=this.h.fftSize;let b=this.Sa=0;for(var c=0;c<a;++c){let f=(this.ve[c]-128)/128;0>f&&(f=-f);
this.Sa<f&&(this.Sa=f);b+=f*f}c=self.ja.af;this.Sa=c(this.Sa);this.te=c(Math.sqrt(b/a))}V(a){this.h.disconnect();this.h.connect(a)}T(){return this.h}ba(){}We(){return{tag:this.da,index:this.he,peak:this.Sa,rms:this.te,binCount:this.h.frequencyBinCount,freqBins:this.ee}}}}"use strict";
{function e(a){return new Promise(b=>setTimeout(b,a))}self.$.ia(class extends self.sa{constructor(a){super(a,"instant-games");this.C=this.ge=!1;this.oe=this.ne=this.B=null;G(this,[["load",b=>this.ig(b)],["loading-progress",b=>this.ng(b)],["start-game",()=>this.Tg()],["quit",()=>this.zg()],["set-player-data",b=>this.Mg(b)],["load-player-data",()=>this.lg()],["share",b=>this.Qg(b)],["custom-update",b=>this.Xf(b)],["switch-game",b=>this.Vg(b)],["change-context",b=>this.Rf(b)],["log-event",b=>this.og(b)],
["load-connected-players",()=>this.kg()],["set-score",b=>this.Ng(b)],["load-player-score",b=>this.mg(b)],["share-leaderboard-update",b=>this.Rg(b)],["load-leaderboard",b=>this.Nf(b)],["create-shortcut",()=>this.Wf()],["subscribe-bot",()=>this.Ug()],["load-ad",b=>this.jg(b)],["show-ad",b=>this.Sg(b)]])}async ig(a){if("instant-games"!==a.exportType)return console.warn("[Instant Games] Project has not been exported with the 'Instant Games' export option, so Instant Games features will be unavailable"),
!1;this.B=window.FBInstant;if(!this.B)return!1;await Promise.race([this.Kf(),e(4E3)]);(this.C=this.ge)?console.info("[Instant Games] Initialized OK"):console.warn("[Instant Games] Initialization timed out after 4 seconds. Continuing with Instant Games disabled.");return this.C}async Kf(){try{await this.B.initializeAsync(),this.ge=!0}catch(a){console.error("[Instant Games] Failed to initialize: ",a)}}ng(a){this.C&&this.B.setLoadingProgress(a.progress)}async Tg(){if(!this.C)return null;const a=this.B;
await a.startGameAsync();a.onPause(()=>t(this,"pause"));const b=a.context,c=a.player,f=a.getEntryPointData();let m="";f&&f.hasOwnProperty("data")&&(m=f.data);return{locale:a.getLocale(),platform:a.getPlatform(),sdkVersion:a.getSDKVersion(),contextId:b.getID(),contextType:b.getType(),playerName:c.getName(),playerPhoto:c.getPhoto(),playerId:c.getID(),entryPointData:m,supportedApis:a.getSupportedAPIs()}}ta(){t(this,"error")}zg(){this.C&&this.B.quit()}async Mg(a){if(this.C)try{await this.B.player.setDataAsync({data:a.data})}catch(b){console.error("[Instant Games] Failed to set player data: ",
b),this.ta()}}async lg(){if(!this.C)return"";try{const a=await this.B.player.getDataAsync(["data"]);if(a&&a.hasOwnProperty("data"))return a.data}catch(a){console.error("[Instant Games] Failed to load player data: ",a),this.ta()}return""}async Qg(a){if(this.C)try{await this.B.shareAsync({intent:a.intent,image:a.image,text:a.text,data:{data:a.data}})}catch(b){console.error("[Instant Games] Failed to share: ",b),this.ta()}}async Xf(a){if(this.C)try{const b={action:"CUSTOM",template:a.templateId,image:a.image,
text:a.text,data:{data:a.data},strategy:a.strategy,notification:a.notification},c=a.cta;c&&(b.cta=c);await this.B.updateAsync(b)}catch(b){console.error("[Instant Games] Error posting custom update: ",b)}}async Vg(a){if(this.C)try{await this.B.switchGameAsync(a.appId,{data:a.data})}catch(b){console.error("[Instant Games] Failed to switch game: ",b),this.ta()}}async Rf(a){if(!this.C)return{isOk:!1};try{const b={},c=a.filter;1===c?b.filters=["NEW_CONTEXT_ONLY"]:2===c?b.filters=["INCLUDE_EXISTING_CHALLENGES"]:
3===c&&(b.filters=["NEW_PLAYERS_ONLY"]);const f=a.minSize,m=a.maxSize;0<=f&&(b.minSize=f);0<=m&&(b.maxSize=m);const n=this.B.context;await n.chooseAsync(b);return{isOk:!0,newContextId:n.getID(),newContextType:n.getType()}}catch(b){if("USER_INPUT"===b.code)return{isOk:!1,cancelled:!0};console.warn("[Instant Games] Failed to change context: ",b);return{isOk:!1}}}og(a){this.C&&this.B.logEvent(a.name,a.valueToSum)}async kg(){if(!this.C)return{isOk:!1};try{return{isOk:!0,connectedPlayers:(await this.B.player.getConnectedPlayersAsync()).map(a=>
({id:a.getID(),name:a.getName(),photo:a.getPhoto()}))}}catch(a){return console.error("[Instant Games] Failed to share: ",a),this.ta(),{isOk:!1}}}async Ng(a){if(!this.C)return!1;try{return await (await this.B.getLeaderboardAsync(a.leaderboardId)).setScoreAsync(a.score),!0}catch(b){return console.error("[Instant Games] Failed to set score: ",b),this.ta(),!1}}async mg(a){if(!this.C)return{isOk:!1};try{const b=await (await this.B.getLeaderboardAsync(a.leaderboardId)).getPlayerEntryAsync();if(!b)throw Error("player has no score");
return{isOk:!0,score:b.getScore(),rank:b.getRank()}}catch(b){return console.error("[Instant Games] Failed to load player score: ",b),this.ta(),{isOk:!1}}}async Rg(a){if(this.C)try{await this.B.updateAsync({action:"LEADERBOARD",name:a.leaderboardId})}catch(b){console.error("[Instant Games] Failed to share leaderboard update: ",b)}}async Nf(a){if(!this.C)return{isOk:!1};const b=a.count,c=a.offset;try{const f=await this.B.getLeaderboardAsync(a.leaderboardId);return{isOk:!0,leaderboardEntries:(0===a.results?
await f.getEntriesAsync(b,c):await f.getConnectedPlayerEntriesAsync(b,c)).map(m=>({score:m.getScore(),rank:m.getRank(),playerId:m.getPlayer().getID(),playerName:m.getPlayer().getName(),playerPhoto:m.getPlayer().getPhoto()}))}}catch(f){return console.error("[Instant Games] Failed to load leaderboard: ",f),this.ta(),{isOk:!1}}}async Wf(){if(!this.C)return!1;try{if(!await this.B.canCreateShortcutAsync())return!1;await this.B.createShortcutAsync();return!0}catch(a){return console.error("[Instant Games] Failed to create shortcut: ",
a),!1}}async Ug(){if(this.C){var a=this.B.player;try{if(!await a.canSubscribeBotAsync())throw Error("not allowed by canSubscribeBotAsync()");await a.subscribeBotAsync();console.log("[Instant Games] Successfully subscribed to bot")}catch(b){console.error("[Instant Games] Failed to subscribe bot: ",b)}}}async jg(a){if(!this.C)return!1;const b=a.placementId;try{const c=0===a.type;let f;f=c?await this.B.getInterstitialAdAsync(b):await this.B.getRewardedVideoAsync(b);await f.loadAsync();c?this.ne=f:this.oe=
f;return!0}catch(c){return console.error("[Instant Games] Failed to load ad: ",c),!1}}async Sg(a){if(!this.C)return!1;a=0===a.type?this.ne:this.oe;if(!a)return!1;try{return await a.showAsync(),!0}catch(b){return console.error("[Instant Games] Failed to show ad: ",b),!1}}})}"use strict";
{function e(a){console.log("[C3 IAP]",a)}self.$.ia(class extends self.sa{constructor(a){super(a,"mobileiap");this.L=null;this.re=[];this.nd=new Set;this.ke=null;D(this,"init",b=>this.Jf(b));D(this,"register",b=>this.Dg(b));D(this,"complete_registration",()=>this.Tf());D(this,"purchase",b=>this.xg(b));D(this,"restore",()=>this.Hg())}Jf(a){e("Initialising");if(this.L=window.store)(a=a["validator-url"])&&(this.L.validator=a),this.L.ready(()=>this.Cg()),this.L.error(b=>this.cg(b)),this.Na("valid",b=>
this.ug(b)),this.Na("approved",b=>this.tg(b)),this.Na("verified",b=>this.wg(b)),this.Na("finished",b=>this.yg(b)),this.Na("owned",b=>this.vg(b)),this.Na("error",(b,c)=>this.Td(c,b))}Na(a,b){this.L.when("product")[a](b)}Cg(){e("store ready");const a=[...this.L.products];t(this,"registration",a)}tg(a){e(`product "${a.alias}" approved, verifying`);a.verify()}wg(a){e(`product "${a.alias}" verified, finishing`);a.finish()}ug(a){this.nd.has(a.id)&&this.Td(a,this.ke);t(this,"product-available",a)}vg(a){t(this,
"product-owned",a)}yg(a){this.nd.delete(a.id);t(this,"purchase-success",a)}Td(a,b){t(this,"purchase-failure",[a,b])}cg(a){this.ke=a;e(a)}Dg(a){const b=a.id;if(!this.L)return null;this.re.push({id:b,alias:b,type:this.L[a.type]})}Tf(){if(this.L){for(const a of this.re)e(`Registering product "${a.alias}"`),this.L.register(a);this.L.refresh()}}xg(a){if(this.L){var b=this.L.get(a);b.valid?(this.nd.add(a),e(`Purchasing product "${a}"`),this.L.order(a)):t(this,"purchase-failure",[b,{code:-1,message:"Unable to purchase invalid product"}])}}Hg(){this.L&&
this.L.refresh()}})}"use strict";
{const e=window.SpeechRecognition||window.webkitSpeechRecognition;self.$.ia(class extends self.sa{constructor(a){super(a,"speech-recognition");this.aa=null;D(this,"get-supported",()=>this.eg());D(this,"request-speech-recognition",b=>this.Gg(b));D(this,"stop-speech-recognition",()=>this.Vd())}eg(){return{isSupported:!!e}}async Gg(a){this.Vd();const b=this.v;"cordova"!==b.s||b.wc()||await b.hf();this.aa=new e;this.aa.lang=a.lang;this.aa.continuous=a.continuous;this.aa.interimResults=a.interimResults;
this.aa.onstart=()=>t(this,"start");this.aa.onend=()=>t(this,"end");this.aa.onerror=c=>{t(this,"error",{message:c.error||"unknown"})};this.aa.onresult=c=>{let f="",m="";for(let n=c.resultIndex,u=c.results.length;n<u;++n){const z=c.results[n];z.isFinal?f+=z[0].transcript:m+=z[0].transcript}t(this,"result",{"final":f,interim:m})};this.aa.start()}Vd(){this.aa&&(this.aa.stop(),this.aa=null)}})}"use strict";
{function e(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.$.ia(class extends self.yd{constructor(b){super(b,"text-input");Q(this,"scroll-to-bottom",c=>this.Kg(c))}pc(b,c){let f;const m=c.type;"textarea"===m?(f=document.createElement("textarea"),f.style.resize="none"):(f=document.createElement("input"),f.type=m);f.style.position="absolute";f.autocomplete="off";f.addEventListener("touchstart",e);f.addEventListener("touchmove",e);f.addEventListener("touchend",
e);f.addEventListener("mousedown",e);f.addEventListener("mouseup",e);f.addEventListener("keydown",a);f.addEventListener("keyup",a);f.addEventListener("click",n=>{n.stopPropagation();R(this,"click",b)});f.addEventListener("dblclick",n=>{n.stopPropagation();R(this,"dblclick",b)});f.addEventListener("input",()=>O(this,"change",b,{text:f.value}));c.id&&(f.id=c.id);this.cb(f,c);return f}cb(b,c){b.value=c.text;b.placeholder=c.placeholder;b.title=c.title;b.disabled=!c.isEnabled;b.readOnly=c.isReadOnly;b.spellcheck=
c.spellCheck;c=c.maxLength;0>c?b.removeAttribute("maxlength"):b.setAttribute("maxlength",c)}Kg(b){b.scrollTop=b.scrollHeight}})}"use strict";
{function e(a){a.stopPropagation()}self.$.ia(class extends self.yd{constructor(a){super(a,"list");Q(this,"set-selected-index",(b,c)=>this.Og(b,c.selectedIndex));Q(this,"add-item",(b,c)=>this.Of(b,c));Q(this,"remove-item",(b,c)=>this.Fg(b,c));Q(this,"set-item",(b,c)=>this.Lg(b,c));Q(this,"clear",b=>this.Sf(b));Q(this,"load-state",(b,c)=>this.Qc(b,c))}pc(a,b){const c=b.isDropdown,f=b.isMultiSelect,m=b.items,n=document.createElement("select");n.style.position="absolute";n.style.userSelect="none";n.style.webkitUserSelect=
"none";n.multiple=f;c||(n.size=2);for(const u of m)n.add(this.Gc(u));n.addEventListener("touchstart",e);n.addEventListener("touchmove",e);n.addEventListener("touchend",e);n.addEventListener("mousedown",e);n.addEventListener("mouseup",e);n.addEventListener("click",u=>{u.stopPropagation();R(this,"click",a,this.Ic(n))});n.addEventListener("dblclick",u=>{u.stopPropagation();R(this,"dblclick",a,this.Ic(n))});n.addEventListener("change",()=>O(this,"change",a,this.Ic(n)));b.id&&(n.id=b.id);this.cb(n,b);
return n}Gc(a){const b=document.createElement("option");b.text=a;return b}Ic(a){const b=a.selectedIndex,c=[];for(let f=0,m=a.length;f<m;++f)a.options[f].selected&&c.push(f);return{selectedIndex:b,selectedIndices:c}}cb(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}Og(a,b){a.selectedIndex=b}Of(a,b){const c=b.index;b=this.Gc(b.text);0>c?a.add(b):a.add(b,c)}Fg(a,b){a.remove(b.index)}Lg(a,b){a.options[b.index].text=b.text}Sf(a){a.innerHTML=""}Qc(a,b){a.innerHTML="";for(const c of b.items)a.add(this.Gc(c));
a.selectedIndex=b.selectedIndex;for(const c of b.selectedIndices)if(b=a.options[c])b.selected=!0}})};
